web_app/config/routes.rb
Rails.application.routes.draw do
  resources :events
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'api/tool', to: 'api#tool'
  get 'api/trees', to: 'api#trees'
  get 'api/events', to: 'api#events'
  post 'api/tool/*id', to: 'api#tool'
  post 'api', to: 'api#index'

  resources :tools
  devise_for :users
  resources :users
  resources :tasks
  resources :items
  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "static#index"
  get "/index.html" => "static#index"
  get "/index2.html" => "static#index2"
  get "/index3.html" => "static#index3"
  get "/form.html" => "static#form"
  get "/form_advanced.html" => "static#form_advanced"
  get "/tables.html" => "static#tables"
  get "/tables_dynamic.html" => "static#tables_dynamic"
  get "/general_elements.html" => "static#general_elements"
  get "/media_gallery.html" => "static#media_gallery"
  get "/typography.html" => "static#typography"
  get "/icons.html" => "static#icons"
  get "/glyphicons.html" => "static#glyphicons"
  get "/widgets.html" => "static#widgets"
  get "/invoice.html" => "static#invoice"
  get "/inbox.html" => "static#inbox"
  get "/calendar.html" => "static#calendar"
  get "/chartjs.html" => "static#chartjs"
  get "/chartjs2.html" => "static#chartjs2"
  get "/morisjs.html" => "static#morisjs"
  get "/echarts.html" => "static#echarts"
  get "/other_charts.html" => "static#other_charts"
  get "/fixed_sidebar.html" => "static#fixed_sidebar"
  get "/fixed_footer.html" => "static#fixed_footer"
  get "/kitchen_sink" => "static#kitchen_sink"
  get "/kitchen8_sink" => "static#kitchen8_sink"


  get "/tasks2.html" => "static#tasks"
  get "/map.html" => "static#map"

end

web_app/app/models/tool.rb
class Tool < ApplicationRecord
end

web_app/app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  before_action :set_tool, only: [:show, :edit, :update, :destroy]

  # GET /tools
  # GET /tools.json
  def index
    @tools = Tool.all
  end

  # GET /tools/1
  # GET /tools/1.json
  def show
  end

  # GET /tools/new
  def new
    @tool = Tool.new
  end

  # GET /tools/1/edit
  def edit
  end

  # POST /tools
  # POST /tools.json
  def create
    @tool = Tool.new(tool_params)

    respond_to do |format|
      if @tool.save
        format.html { redirect_to @tool, notice: 'Tool was successfully created.' }
        format.json { render :show, status: :created, location: @tool }
      else
        format.html { render :new }
        format.json { render json: @tool.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tools/1
  # PATCH/PUT /tools/1.json
  def update
    respond_to do |format|
      if @tool.update(tool_params)
        format.html { redirect_to @tool, notice: 'Tool was successfully updated.' }
        format.json { render :show, status: :ok, location: @tool }
      else
        format.html { render :edit }
        format.json { render json: @tool.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tools/1
  # DELETE /tools/1.json
  def destroy
    @tool.destroy
    respond_to do |format|
      format.html { redirect_to tools_url, notice: 'Tool was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tool
      @tool = Tool.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tool_params
      params.require(:tool).permit(:name, :bt_id, :type, :latitude, :longitude)
    end
end

web_app/app/helpers/tools_helper.rb
module ToolsHelper
end

web_app/app/views/tools/_form.html.slim
= form_for @tool do |f|
  - if @tool.errors.any?
    #error_explanation
      h2 = "#{pluralize(@tool.errors.count, "error")} prohibited this tool from being saved:"
      ul
        - @tool.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :bt_id
    = f.text_field :bt_id
  .field
    = f.label :type
    = f.text_field :type
  .field
    = f.label :latitude
    = f.text_field :latitude
  .field
    = f.label :longitude
    = f.text_field :longitude
  .actions = f.submit

web_app/app/views/tools/edit.html.slim
h1 Editing tool

== render 'form'

=> link_to 'Show', @tool
'|
=< link_to 'Back', tools_path

web_app/app/views/tools/index.html.slim
h1 Listing tools

table
  thead
    tr
      th Name
      th Bt
      th Type
      th Latitude
      th Longitude
      th
      th
      th

  tbody
    - @tools.each do |tool|
      tr
        td = tool.name
        td = tool.bt_id
        td = tool.type
        td = tool.latitude
        td = tool.longitude
        td = link_to 'Show', tool
        td = link_to 'Edit', edit_tool_path(tool)
        td = link_to 'Destroy', tool, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Tool', new_tool_path

web_app/app/views/tools/new.html.slim
h1 New tool

== render 'form'

= link_to 'Back', tools_path

web_app/app/views/tools/show.html.slim
p#notice = notice

p
  strong Name:
  = @tool.name
p
  strong Bt:
  = @tool.bt_id
p
  strong Type:
  = @tool.type
p
  strong Latitude:
  = @tool.latitude
p
  strong Longitude:
  = @tool.longitude

=> link_to 'Edit', edit_tool_path(@tool)
'|
=< link_to 'Back', tools_path