web_app/config/routes.rb
Rails.application.routes.draw do
  resources :events
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'api/tool', to: 'api#tool'
  get 'api/trees', to: 'api#trees'
  get 'api/events', to: 'api#events'
  post 'api/tool/*id', to: 'api#tool'
  post 'api', to: 'api#index'

  resources :tools
  devise_for :users
  resources :users
  resources :tasks
  resources :items
  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "static#index"
  get "/index.html" => "static#index"
  get "/index2.html" => "static#index2"
  get "/index3.html" => "static#index3"
  get "/form.html" => "static#form"
  get "/form_advanced.html" => "static#form_advanced"
  get "/tables.html" => "static#tables"
  get "/tables_dynamic.html" => "static#tables_dynamic"
  get "/general_elements.html" => "static#general_elements"
  get "/media_gallery.html" => "static#media_gallery"
  get "/typography.html" => "static#typography"
  get "/icons.html" => "static#icons"
  get "/glyphicons.html" => "static#glyphicons"
  get "/widgets.html" => "static#widgets"
  get "/invoice.html" => "static#invoice"
  get "/inbox.html" => "static#inbox"
  get "/calendar.html" => "static#calendar"
  get "/chartjs.html" => "static#chartjs"
  get "/chartjs2.html" => "static#chartjs2"
  get "/morisjs.html" => "static#morisjs"
  get "/echarts.html" => "static#echarts"
  get "/other_charts.html" => "static#other_charts"
  get "/fixed_sidebar.html" => "static#fixed_sidebar"
  get "/fixed_footer.html" => "static#fixed_footer"
  get "/kitchen_sink" => "static#kitchen_sink"
  get "/kitchen8_sink" => "static#kitchen8_sink"


  get "/tasks2.html" => "static#tasks"
  get "/map.html" => "static#map"

end

web_app/app/views/layouts/shared/_footer.html.erb
<div class="pull-right">
  Stilbruch - a TECHFEST 2018 project
</div>
<div class="clearfix"></div>

web_app/app/views/layouts/shared/_leftnav.html.erb
<div class="navbar nav_title" style="border: 0;">
  <a href="index.html" class="site_title"><i class="logo" style="background-image: url('/images/logo.png');width: 60px;display: inline-block;height: 60px;background-size: contain;background-repeat: no-repeat;border: none;"></i> <span style="vertical-align: top;">Arbo</span></a>
</div>

<div class="clearfix"></div>

<!-- menu profile quick info -->
<div class="profile clearfix">
  <div class="profile_pic">
    <img src="/images/img.jpg" alt="..." class="img-circle profile_img">
  </div>
  <div class="profile_info">
    <span>Welcome,</span>
    <h2>John Doe</h2>
  </div>
</div>
<!-- /menu profile quick info -->

<br />

<!-- sidebar menu -->
<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
  <div class="menu_section">
    <h3>Stilbruch</h3>
    <ul class="nav side-menu">
      <li><a href="index.html"><i class="fa fa-home"></i> Landing Page</a></li>
      <li><%= link_to tasks_path do%><i class="fa fa-check-square"></i> Tasks<%end%></li>
      <li><%= link_to items_path do%><i class="fa fa-tree"></i> Objects<%end%></li>
      <li><%= link_to tools_path do%><i class="fa fa-tree"></i> Tools<%end%></li>
      <li><%= link_to users_path do%><i class="fa fa-users"></i> Users<%end%></li>

      <li><a href="map.html"><i class="fa fa-map"></i> Map</a></li>
    </ul>
  </div>


  <!-- <div class="menu_section">
    <h3>General</h3>
    <ul class="nav side-menu">
      <li><a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li><a href="index.html">Dashboard</a></li>
          <li><a href="index2.html">Dashboard2</a></li>
          <li><a href="index3.html">Dashboard3</a></li>
        </ul>
      </li>
      <li><a><i class="fa fa-edit"></i> Forms <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li><a href="form.html">General Form</a></li>
          <li><a href="form_advanced.html">Advanced Components</a></li>
          <li><a href="form_validation.html">Form Validation</a></li>
          <li><a href="form_wizards.html">Form Wizard</a></li>
          <li><a href="form_upload.html">Form Upload</a></li>
          <li><a href="form_buttons.html">Form Buttons</a></li>
        </ul>
      </li>
      <li><a><i class="fa fa-desktop"></i> UI Elements <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li><a href="general_elements.html">General Elements</a></li>
          <li><a href="media_gallery.html">Media Gallery</a></li>
          <li><a href="typography.html">Typography</a></li>
          <li><a href="icons.html">Icons</a></li>
          <li><a href="glyphicons.html">Glyphicons</a></li>
          <li><a href="widgets.html">Widgets</a></li>
          <li><a href="invoice.html">Invoice</a></li>
          <li><a href="inbox.html">Inbox</a></li>
          <li><a href="calendar.html">Calendar</a></li>
        </ul>
      </li>
      <li><a><i class="fa fa-table"></i> Tables <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li><a href="tables.html">Tables</a></li>
          <li><a href="tables_dynamic.html">Table Dynamic</a></li>
        </ul>
      </li>
      <li><a><i class="fa fa-bar-chart-o"></i> Data Presentation <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li><a href="chartjs.html">Chart JS</a></li>
          <li><a href="chartjs2.html">Chart JS2</a></li>
          <li><a href="morisjs.html">Moris JS</a></li>
          <li><a href="echarts.html">ECharts</a></li>
          <li><a href="other_charts.html">Other Charts</a></li>
        </ul>
      </li>
      <li><a><i class="fa fa-clone"></i>Layouts <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li><a href="fixed_sidebar.html">Fixed Sidebar</a></li>
          <li><a href="fixed_footer.html">Fixed Footer</a></li>
        </ul>
      </li>
    </ul>
  </div>
  <div class="menu_section">
    <h3>Live On</h3>
    <ul class="nav side-menu">
      <li><a><i class="fa fa-bug"></i> Additional Pages <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li><a href="e_commerce.html">E-commerce</a></li>
          <li><a href="projects.html">Projects</a></li>
          <li><a href="project_detail.html">Project Detail</a></li>
          <li><a href="contacts.html">Contacts</a></li>
          <li><a href="profile.html">Profile</a></li>
        </ul>
      </li>
      <li><a><i class="fa fa-windows"></i> Extras <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li><a href="page_403.html">403 Error</a></li>
          <li><a href="page_404.html">404 Error</a></li>
          <li><a href="page_500.html">500 Error</a></li>
          <li><a href="plain_page.html">Plain Page</a></li>
          <li><a href="login.html">Login Page</a></li>
          <li><a href="pricing_tables.html">Pricing Tables</a></li>
        </ul>
      </li>
      <li><a><i class="fa fa-sitemap"></i> Multilevel Menu <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li><a href="#level1_1">Level One</a>
            <li><a>Level One<span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu">
                <li class="sub_menu"><a href="level2.html">Level Two</a>
                </li>
                <li><a href="#level2_1">Level Two</a>
                </li>
                <li><a href="#level2_2">Level Two</a>
                </li>
              </ul>
            </li>
            <li><a href="#level1_2">Level One</a>
            </li>
        </ul>
          </li>
          <li><a href="javascript:void(0)"><i class="fa fa-laptop"></i> Landing Page <span class="label label-success pull-right">Coming Soon</span></a></li>
    </ul>
  </div> -->

</div>
<!-- /sidebar menu -->

<!-- /menu footer buttons -->
<div class="sidebar-footer hidden-small">
  <a data-toggle="tooltip" data-placement="top" title="Settings">
    <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
  </a>
  <a data-toggle="tooltip" data-placement="top" title="FullScreen">
    <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
  </a>
  <a data-toggle="tooltip" data-placement="top" title="Lock">
    <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
  </a>
  <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
    <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
  </a>
</div>
<!-- /menu footer buttons -->

web_app/app/views/layouts/shared/_topnav.html.erb
<div class="nav toggle">
  <a id="menu_toggle"><i class="fa fa-bars"></i></a>
</div>

<ul class="nav navbar-nav navbar-right">
  <li class="">
    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
      <img src="images/img.jpg" alt="">John Doe
      <span class=" fa fa-angle-down"></span>
    </a>
    <ul class="dropdown-menu dropdown-usermenu pull-right">
      <li><a href="javascript:;"> Profile</a></li>
      <li>
        <a href="javascript:;">
          <span class="badge bg-red pull-right">50%</span>
          <span>Settings</span>
        </a>
      </li>
      <li><a href="javascript:;">Help</a></li>
      <li><a href="login.html"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
    </ul>
  </li>

  <li role="presentation" class="dropdown">
    <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
      <i class="fa fa-envelope-o"></i>
      <span class="badge bg-green">6</span>
    </a>
    <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
      <li>
        <a>
          <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
          <span>
            <span>John Smith</span>
            <span class="time">3 mins ago</span>
          </span>
          <span class="message">
            Film festivals used to be do-or-die moments for movie makers. They were where...
          </span>
        </a>
      </li>
      <li>
        <a>
          <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
          <span>
            <span>John Smith</span>
            <span class="time">3 mins ago</span>
          </span>
          <span class="message">
            Film festivals used to be do-or-die moments for movie makers. They were where...
          </span>
        </a>
      </li>
      <li>
        <a>
          <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
          <span>
            <span>John Smith</span>
            <span class="time">3 mins ago</span>
          </span>
          <span class="message">
            Film festivals used to be do-or-die moments for movie makers. They were where...
          </span>
        </a>
      </li>
      <li>
        <a>
          <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
          <span>
            <span>John Smith</span>
            <span class="time">3 mins ago</span>
          </span>
          <span class="message">
            Film festivals used to be do-or-die moments for movie makers. They were where...
          </span>
        </a>
      </li>
      <li>
        <div class="text-center">
          <a>
            <strong>See All Alerts</strong>
            <i class="fa fa-angle-right"></i>
          </a>
        </div>
      </li>
    </ul>
  </li>
</ul>